### ISSUE TITLE
OPNsense 22.7_4 settings tab php errors

### ISSUE THREAD

**Issue by dimitrijp** [crowdsecurity/opnsense-plugin-crowdsec#31]
Installed the plugin on 22.7_4, when clicking on Services-Crowdsec-settings ... php error is detected and unable to access the settings tab...

here are the errors;

System Information:
```
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71
FreeBSD 13.1-RELEASE stable/22.7-n250212-a26d6065f1f SMP amd64
OPNsense 22.7_4 909dcabd5
Plugins os-acme-client-3.11 os-crowdsec-1.0 os-freeradius-1.9.19_1 os-haproxy-3.10 
Time Mon, 01 Aug 2022 11:17:39 +0200
OpenSSL 1.1.1q  5 Jul 2022
Python 3.9.13
PHP 8.0.20
```

PHP Errors:

```
[01-Aug-2022 11:17:17 Europe/Ljubljana] ParseError: syntax error, unexpected identifier "readonly" in /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_form_input_tr.volt.php:20
Stack trace:
#0 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, false)
#1 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'layout_partials...', false, false)
#2 [internal function]: Phalcon\Mvc\View->partial('layout_partials...', Array)
#3 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_base_form.volt.php(63): Phalcon\Mvc\View\Engine\AbstractEngine->partial('layout_partials...', Array)
#4 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, false)
#5 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'layout_partials...', false, false)
#6 [internal function]: Phalcon\Mvc\View->partial('layout_partials...', Array)
#7 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_crowdsec_general.volt.php(178): Phalcon\Mvc\View\Engine\AbstractEngine->partial('layout_partials...', Array)
#8 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, true)
#9 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'OPNsense/CrowdS...', true)
#10 [internal function]: Phalcon\Mvc\View->processRender('general', 'index', Array)
#11 [internal function]: Phalcon\Mvc\View->render('general', 'index')
#12 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/crowdsec/ge...')
#13 {main}
[01-Aug-2022 11:17:39 Europe/Ljubljana] ParseError: syntax error, unexpected identifier "readonly" in /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_form_input_tr.volt.php:20
Stack trace:
#0 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, false)
#1 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'layout_partials...', false, false)
#2 [internal function]: Phalcon\Mvc\View->partial('layout_partials...', Array)
#3 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_base_form.volt.php(63): Phalcon\Mvc\View\Engine\AbstractEngine->partial('layout_partials...', Array)
#4 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, false)
#5 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'layout_partials...', false, false)
#6 [internal function]: Phalcon\Mvc\View->partial('layout_partials...', Array)
#7 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_crowdsec_general.volt.php(178): Phalcon\Mvc\View\Engine\AbstractEngine->partial('layout_partials...', Array)
#8 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, true)
#9 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'OPNsense/CrowdS...', true)
#10 [internal function]: Phalcon\Mvc\View->processRender('general', 'index', Array)
#11 [internal function]: Phalcon\Mvc\View->render('general', 'index')
#12 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/crowdsec/ge...')
#13 {main}

```

**Comment by mmetc** [comment]
Hi, have you tried to remove the cache files? I don't remember having used a "readonly" tag, but it's certainly not in the 1.0 plugin

**Comment by dimitrijp** [comment]
hello...reboot was needed after installation of plugin. Now its working.
